name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Sync to S3 using AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync . s3://focuspuzzles3bucket --region ap-northeast-2 --exact-timestamps \
          --exclude ".git/*" --exclude ".git"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 120
        debug: true
        script: |
          # 배포 디렉토리 설정
          DEPLOY_DIR="/home/ec2-user/focuspuzzle"

          # AWS CLI 설치 확인
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/aws-cli-v2-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

          # S3에서 최신 파일 동기화
          aws s3 sync s3://focuspuzzles3bucket $DEPLOY_DIR --region ap-northeast-2 || exit 1

          # 디렉토리 권한 설정
          chmod -R 755 $DEPLOY_DIR
          echo "Deployment completed successfully"
