name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Sync to S3 using AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync . s3://focuspuzzles3bucket --region ap-northeast-2 --exact-timestamps \
          --exclude ".git/*" --exclude ".git"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # 배포 디렉토리 설정
          DEPLOY_DIR="/home/ec2-user/focuspuzzle"

          # 디렉토리가 없는 경우 생성
          if [ ! -d "$DEPLOY_DIR" ]; then
            mkdir -p $DEPLOY_DIR
          fi

          # S3에서 최신 파일 다운로드 (기존 파일 유지)
          aws s3 sync s3://focuspuzzles3bucket $DEPLOY_DIR --region ap-northeast-2

          # 디렉토리 권한 설정
          chmod -R 755 $DEPLOY_DIR
